- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/host
  value: ((terraform_outputs.production_credhub_rds_host))

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/port
  value: ((terraform_outputs.production_credhub_rds_port))

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/username
  value: ((terraform_outputs.production_credhub_rds_username))

- type: replace
  path: /instance_groups/name=credhub/jobs/name=credhub/properties/credhub/data_storage/password
  value: ((terraform_outputs.production_credhub_rds_password))
