deployment_name: credhub-staging
common_name: credhub.fr-stage.cloud.gov
instances: 2
azs: [z2,z1]
network_name: staging-credhub
credhub_vm_type: t3.medium
credhub_lb_vm_extension: staging-credhub-lb
pipeline-tasks-git-url: https://github.com/18F/cg-pipeline-tasks
pipeline-tasks-git-branch: master